version: '3'
volumes:
  etc_wireguard:
  
services:
  go:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
      - ./public/:/app/public